### ISSUE TITLE
Check for Error 404 and skip these links instead of crashing.

### ISSUE THREAD

**Issue by Ryuichiro** [MakeYourLifeEasier/Wuxiaworld-2-eBook#12]
I encountered the problem that an index contains a dead link after one that has 2 chapters.
Would be nice when the script could check for Error 404, skip these links and continue.
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "wuxiaworld2ebook.py", line 60, in button_press
    getify.download(bulk_list[x], str(s_chapter) + ".xhtml")
  File "C:\Users\USERNAME\Desktop\epubs\Wuxiaworld-2-eBook-master\getify.py", line 28, in download
    with urllib.request.urlopen(url) as response, open(file_name, 'wb') as out_file:
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```
![Screenshot](https://i.imgur.com/ppA4qdl.png)
Index: http://www.wuxiaworld.com/ast-index/
Chapter 1183: http://www.wuxiaworld.com/ast-index/ast-chapter-1183-1184/
Chapter 1184: http://www.wuxiaworld.com/ast-index/ast-chapter-1184

**Comment by MrHaCkEr** [comment]
It's already implemented in the version I have on my desktop, but because of exams the update release will be delayed. Check back in a month, till then the update should be live.

**Comment by Ryuichiro** [comment]
Thanks, for now I will try and write a dirty workaround in my local files. ^^

**Comment by MrHaCkEr** [comment]
Just use requests in the download function, line 19 in getify.py, and check the status code with the `status_code` method of request to check for error 404. Or simply use try and except.

If the workaround isn't too dirty, you can submit a pull request :D

**Comment by Ryuichiro** [comment]
Couldn't find a way to create a pull request for an issue so I created a new one an referenced it. ^^

**Comment by MrHaCkEr** [comment]
Merged it - Thanks for your contribution 👍
