### ISSUE TITLE
MacOS + python 3.6 users 

### ISSUE THREAD

**Issue by tansr7** [MakeYourLifeEasier/Wuxiaworld-2-eBook#35]
#### Font not found

>Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 1699, in __call__
    return self.func(*args)
  File "wuxiaworld2ebook.py", line 59, in button_press
    getify.cover_generator(raw_info[4], s_chapter, str(e_chapter))
  File "/Users/stan170/Desktop/wuxia/Wuxiaworld-2-eBook/getify.py", line 101, in cover_generator
    thefont = ImageFont.truetype("arial.ttf", 75)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/ImageFont.py", line 259, in truetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/ImageFont.py", line 143, in __init__
    self.font = core.getfont(font, size, index, encoding, layout_engine=layout_engine)
OSError: cannot open resource

- PIL.ImageFont.truetype doesn't search in __Mac__ font folder unlike __Windows__.. 
- Soln: drop Arial.ttf in working dir/ change dir

#### SSL: CERTIFICATE_VERIFY_FAILED for python 3.6 

>URL: http://www.wuxiaworld.com/novel/7-killers/7k-chapter-1, URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)
URL: http://www.wuxiaworld.com/novel/7-killers/7k-chapter-2, URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 1699, in __call__
    return self.func(*args)
  File "wuxiaworld2ebook.py", line 85, in button_press
    getify.generate(file_list, raw_info[0], raw_info[3], raw_info[2], reset, str(e_chapter), cleanup=cleanup)
  File "/Users/stan170/Desktop/wuxia/Wuxiaworld-2-eBook/getify.py", line 172, in generate
    epub.write(html, "OEBPS/"+basename)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/zipfile.py", line 1594, in write
    zinfo = ZipInfo.from_file(filename, arcname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/zipfile.py", line 484, in from_file
    st = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '7 Killers/7k-chapter-1.xhtml'

- ["Python 3.6 on OSX has no certificates at all, and can't validate any SSL connections"](https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error)
- due to sql + ulrlib.error 
- Run the _Install Certificates.command_ in python folder

Thought it might be useful for OSx noobs like me so that they don't have to google. 

Thanks for all your work

**Comment by MrHaCkEr** [comment]
I'm sorry for your mediocre experience with this script. 

I'm currently working on an implementation of this script in a django webapp as a side project. That will fix the inconsistencies in quality between operating systems and make the whole process more user friendly.

For now I'll leave this issue open and mention it in the ReadMe. If I find the time I'll do some QA on a mac.

Tha is for reporting the issue!

**Comment by MichaelGuardian** [comment]
Both issues fixed on [novel-ebook.com](https://novel-ebook.com)
